name: apk_automation_dart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  build_cli_annotations: ^2.1.0
  equatable: ^2.0.5
  googleapis: ^13.1.0
  googleapis_auth: ^1.5.1
  melos: ^5.2.2
  # path: ^1.8.0
  advanced_console: ^0.0.1
  cli_spin: ^1.0.1

dev_dependencies:
  build_cli: ^2.2.3
  build_runner: ^2.4.8
  lints: ^3.0.0
  test: ^1.24.0
